# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  eboy.gr:
    site_hosts:
      - canonical: eboy.gr
        redirects:
          - www.eboy.gr

      - canonical: simple-city.eboy.gr
        redirects:
          - www.simple-city.eboy.gr

      - canonical: monk.eboy.gr
        redirects:
          - www.monk.eboy.gr

    local_path: ../site
    branch: main
    repo: git@github.com:Giannisduke/eboy.gr.git
    repo_subtree_path: site

    multisite:
      enabled: false
      subdomains: true

    ssl:
      enabled: true
      provider: letsencrypt

    cache:
      enabled: false

    env:
      wp_env: staging
      wp_home: https://eboy.gr
      wp_siteurl: https://eboy.gr/wp
      domain_current_site: eboy.gr
      path_current_site: /
